server:
  port: 8081

telegram:
  username: "@ApplicationHelperBot"
  botToken: <token>
  webHookPath: <path>
  botPath: webhook

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url:  jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver
