server:
  port: 8080

telegram:
  username: "@ApplicationHelperBot"
  botToken: 5961427565:AAGSzRKM-KfY7ZiVfCaNQ6_VxkniGNKB-Xs
  webHookPath: https://www.mstelegrambot.com/
  telegramUrl: https://api.telegram.org/bot
  botPath: webhook


